### ISSUE TITLE
qualche dritta

### ISSUE THREAD

**Issue by moebiusmania** [LucaArgentieri/care-of-u#1]
ti lascio alcuni feedback ora che ho spulciato un po il codice:

- aggiungi **sempre** un file di licenza, https://choosealicense.com/ ti può aiutare e in genere la licenza MIT compre gran parte dei casi
- non lasciare il **readme.md** vuoto , aggiungi almeno le istruzioni per l'installazione e i requisiti (*versione minima di Node.js, account firebase, yarn, ecc)
- scegli una convenzione per l'ordine degli import, mediamente si preferisce scrivere prima quelli "assoluti" dei pacchetti NPM, tipo `import react from 'react'` e dopo quelli relativi come quelli dei file interni del progetto tipo `import Filter from './components/filter`. Non c'è una regola fissa ma cerca di mantenere l'ordine costante nei file per leggibilità.
- comincia a preparare il setup dello store condiviso tra i componenti, con lo stato di React o qualunque altra libreria, secondo me già un minimo ora farebbe comodo (*per esempio per leggere i valori dei settings*) e poi appena aggiungerai altre funzionalità inizierà a farsi sentire il bisogno...

per il resto mi sembra a posto 😎

**Comment by LucaArgentieri** [comment]
Grazie mille Salvatore! 💪
